version: '3.8'

services:
  dtownbeats:
    image: angablade/dtownbeats:latest
    container_name: dtownbeats
    volumes:
      - ./lyrics:/app/lyrics
      - ./music:/app/music
      - ./config:/app/config
      - ./models:/app/models
      - ./albumart:/app/albumart
      - ./metacache:/app/metacache
      - ./static:/app/static
    environment:
      # Discord Bot Configuration
      - BOT_TOKEN=YOUR_BOT_TOKEN_HERE
      - BOT_OWNER_ID=1234567890123456
      
      # MusicBrainz Configuration
      - MUSICBRAINZ_USERAGENT=dtownbeats
      - MUSICBRAINZ_VERSION=1.1
      - MUSICBRAINZ_CONTACT=youremail@example.com
      
      # Performance & Limits
      - EXECUTOR_MAX_WORKERS=10
      - QUEUE_PAGE_SIZE=10
      - HISTORY_PAGE_SIZE=10
      - TIMEOUT_TIME=60
      
      # Web Panel Configuration
      - WEB_PORT=80
      - SESSION_SECRET=your_very_secure_random_string_here_at_least_32_chars
      - DISCORD_CLIENT_ID=your_discord_app_client_id
      - DISCORD_CLIENT_SECRET=your_discord_app_client_secret
      
      # Optional: Disable init script auto-update
      # - DISABLE_INIT_UPDATE=false
      # - AUTO_UPDATE_INIT=true
    ports:
      - "3333:80"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dtownbeats_network

networks:
  dtownbeats_network:
    driver: bridge
